//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivoPagamentoJudiciais.Data {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Querys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Querys() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VivoPagamentoJudiciais.Data.Querys", typeof(Querys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select fExcel.idExcelFileColumn,grc.nomePropriedade,fExcel.ColumnPosition,fExcel.HeaderName
        ///from VivoPagamentoJudiciais.dbo.geracaoArquivoClasse grc
        ///join VivoPagamentoJudiciais.dbo.deparaexcel dpeexcel on grc.idgeracaoArquivoClasse = dpeexcel.idgeracaoArquivoClasse
        ///join VivoPagamentoJudiciais.dbo.excelfilecolumn fExcel on dpeexcel.idExcelFileColumn = fExcel.idExcelFileColumn
        ///where grc.idGeracaoArquivo =@IdGeracaoArquivo.
        /// </summary>
        public static string GetExcelDePara {
            get {
                return ResourceManager.GetString("GetExcelDePara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select gr.*,ta.* ,dp.*,tdp.*,email.*
        ///from VivoPagamentoJudiciais.dbo.geracaoarquivo gr 
        ///join VivoPagamentoJudiciais.dbo.tipoarquivo ta 
        ///on ta.idTipoArquivo = gr.idTipoArquivo
        ///left join VivoPagamentoJudiciais.dbo.geracaoarquivodepara dp on dp.idGeracaoArquivo = gr.idGeracaoArquivo
        ///left join VivoPagamentoJudiciais.dbo.templatearquivodepara tdp on dp.idGeracaoArquivoDePara = tdp.idGeracaoArquivoDePara
        ///left join VivoPagamentoJudiciais.dbo.GeracaoArquivoEmail grEmail on grEmail.idGeracaoArquivo =gr.idGeracaoArqu [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string GetGeracaoArquivo {
            get {
                return ResourceManager.GetString("GetGeracaoArquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select grc.*, csv.*       
        ///from  VivoPagamentoJudiciais.dbo.geracaoarquivoclasse grc 
        ///left join  VivoPagamentoJudiciais.dbo.importcsv impCsv on grc.idGeracaoArquivoClasse = impCsv.idGeracaoArquivoClasse 
        ///left join  VivoPagamentoJudiciais.dbo.csvfilecolumn csv on impCsv.idcsvfilecolumn = csv.idcsvfilecolumn
        ///where grc.idGeracaoArquivo =@IdGeracaoArquivo.
        /// </summary>
        public static string GetGeracaoArquivoClasse {
            get {
                return ResourceManager.GetString("GetGeracaoArquivoClasse", resourceCulture);
            }
        }
    }
}
