//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivoPagamentoJudiciais.Utilities {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Variables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Variables() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VivoPagamentoJudiciais.Utilities.Variables", typeof(Variables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adquira.
        /// </summary>
        public static string Adquira {
            get {
                return ResourceManager.GetString("Adquira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AdquiraServiceStartup.
        /// </summary>
        public static string AdquiraServiceStartup {
            get {
                return ResourceManager.GetString("AdquiraServiceStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DataGenerateWithExpression.
        /// </summary>
        public static string DataGenerateWithExpression {
            get {
                return ResourceManager.GetString("DataGenerateWithExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DowloadFile.
        /// </summary>
        public static string DowloadFile {
            get {
                return ResourceManager.GetString("DowloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ExcelTreatFile.
        /// </summary>
        public static string ExcelTreatFile {
            get {
                return ResourceManager.GetString("ExcelTreatFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GenerateFile.
        /// </summary>
        public static string GenerateFile {
            get {
                return ResourceManager.GetString("GenerateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GetExcelDePara.
        /// </summary>
        public static string GetExcelDePara {
            get {
                return ResourceManager.GetString("GetExcelDePara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GetGeracaoArquivo.
        /// </summary>
        public static string GetGeracaoArquivo {
            get {
                return ResourceManager.GetString("GetGeracaoArquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GetGeracaoArquivoClasse.
        /// </summary>
        public static string GetGeracaoArquivoClasse {
            get {
                return ResourceManager.GetString("GetGeracaoArquivoClasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a iso-8859-1.
        /// </summary>
        public static string ISO8859_1 {
            get {
                return ResourceManager.GetString("ISO8859_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LoginSite.
        /// </summary>
        public static string LoginSite {
            get {
                return ResourceManager.GetString("LoginSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mapping.
        /// </summary>
        public static string Mapping {
            get {
                return ResourceManager.GetString("Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processum.
        /// </summary>
        public static string Processum {
            get {
                return ResourceManager.GetString("Processum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ProcessumServiceStartup.
        /// </summary>
        public static string ProcessumServiceStartup {
            get {
                return ResourceManager.GetString("ProcessumServiceStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Schedule - Startup.
        /// </summary>
        public static string ScheduleStartup {
            get {
                return ResourceManager.GetString("ScheduleStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a StreamingExchange.
        /// </summary>
        public static string StreamingExchange {
            get {
                return ResourceManager.GetString("StreamingExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TreatFile.
        /// </summary>
        public static string TreatFile {
            get {
                return ResourceManager.GetString("TreatFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VivoPagamento.
        /// </summary>
        public static string VivoPagamento {
            get {
                return ResourceManager.GetString("VivoPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VivoPagamentoServiceStartup.
        /// </summary>
        public static string VivoPagamentoServiceStartup {
            get {
                return ResourceManager.GetString("VivoPagamentoServiceStartup", resourceCulture);
            }
        }
    }
}
